version: "2"
run:
  timeout: 10m10s

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - unconvert
    - unused
    - whitespace
  settings:
    gosec:
      config:
        G301: "0755"
  exclusions:
    rules:
      - path: _test\.go
        text: "Error return value of `.*` is not checked" # for intentional defer cleanup
      - path: _test\.go
        text: "G104: Errors unhandled" # for intentional defer cleanup

formatters:
  enable:
    - gofmt
    - goimports

  # don't enable:
  #  - asciicheck
  #  - depguard
  #  - dogsled
  #  - dupl
  #  - funlen
  #  - gochecknoinits
  #  - gochecknoglobals
  #  - gocognit
  #  - goconst
  #  - gocyclo
  #  - gomnd
  #  - godot
  #  - godox
  #  - goerr113
  #  - lll
  #  - prealloc
  #  - revive
  #  - stylecheck
  #  - staticcheck
  #  - structcheck
  #  - testpackage
  #  - unparam
  #  - wsl
